spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqldb:3306/insurance_app
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
